//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebsite.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myWebsiteEntities : DbContext
    {
        public myWebsiteEntities()
            : base("name=myWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Deneyimler> Deneyimlers { get; set; }
        public virtual DbSet<Eğitimlerim> Eğitimlerim { get; set; }
        public virtual DbSet<Hobilerim> Hobilerims { get; set; }
        public virtual DbSet<Iletisim> Iletisims { get; set; }
        public virtual DbSet<Sertifikalar> Sertifikalars { get; set; }
        public virtual DbSet<Yetenekler> Yeteneklers { get; set; }
        public virtual DbSet<Hakkimda> Hakkimdas { get; set; }
    }
}
